### ISSUE TITLE
[Request] Inject in Ragexe.exe

### ISSUE THREAD

**Issue by vhinz2145** [alisonrag/NetRedirect-WinDetour#7]
Hello Alisonrag,

I'm a newbie and i dont know how to inject this in Ragexe. How can i inject this sir? I already tried other options just to run Xkore1 and Xkore0 but still i'm having problem either "Unable to inject NetRedirect", "Waiting for the Ragnarok Online client to connect to X-Kore..." or "Connecting (103.169.66.142:51000)... connected"

**Comment by vhinz2145** [comment]
sir why you closed this?

**Comment by alisonrag** [comment]
this project is about the dll, not related on how to inject

**Comment by vhinz2145** [comment]
> this project is about the dll, not related on how to inject

because you're not even responding to my comment. I'm a newbie and i already try those option that they/you gave. I'm not pretty sure if i did it correctly that's why i'm asking.
